# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wwwe/v4a/ViPERFX_RE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wwwe/v4a/ViPERFX_RE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wwwe/v4a/ViPERFX_RE/CMakeFiles /home/wwwe/v4a/ViPERFX_RE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wwwe/v4a/ViPERFX_RE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pffft_core

# Build rule for target.
pffft_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pffft_core
.PHONY : pffft_core

# fast build rule for target.
pffft_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pffft_core.dir/build.make CMakeFiles/pffft_core.dir/build
.PHONY : pffft_core/fast

#=============================================================================
# Target rules for targets named v4a_re

# Build rule for target.
v4a_re: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v4a_re
.PHONY : v4a_re

# fast build rule for target.
v4a_re/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/build
.PHONY : v4a_re/fast

#=============================================================================
# Target rules for targets named IEMDSP

# Build rule for target.
IEMDSP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IEMDSP
.PHONY : IEMDSP

# fast build rule for target.
IEMDSP/fast:
	$(MAKE) $(MAKESILENT) -f IEMDSP/CMakeFiles/IEMDSP.dir/build.make IEMDSP/CMakeFiles/IEMDSP.dir/build
.PHONY : IEMDSP/fast

#=============================================================================
# Target rules for targets named ViPERDSP

# Build rule for target.
ViPERDSP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ViPERDSP
.PHONY : ViPERDSP

# fast build rule for target.
ViPERDSP/fast:
	$(MAKE) $(MAKESILENT) -f ViPERDSP/CMakeFiles/ViPERDSP.dir/build.make ViPERDSP/CMakeFiles/ViPERDSP.dir/build
.PHONY : ViPERDSP/fast

ViPERDSP/viper/utils/pffft.o: ViPERDSP/viper/utils/pffft.c.o
.PHONY : ViPERDSP/viper/utils/pffft.o

# target to build an object file
ViPERDSP/viper/utils/pffft.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pffft_core.dir/build.make CMakeFiles/pffft_core.dir/ViPERDSP/viper/utils/pffft.c.o
.PHONY : ViPERDSP/viper/utils/pffft.c.o

ViPERDSP/viper/utils/pffft.i: ViPERDSP/viper/utils/pffft.c.i
.PHONY : ViPERDSP/viper/utils/pffft.i

# target to preprocess a source file
ViPERDSP/viper/utils/pffft.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pffft_core.dir/build.make CMakeFiles/pffft_core.dir/ViPERDSP/viper/utils/pffft.c.i
.PHONY : ViPERDSP/viper/utils/pffft.c.i

ViPERDSP/viper/utils/pffft.s: ViPERDSP/viper/utils/pffft.c.s
.PHONY : ViPERDSP/viper/utils/pffft.s

# target to generate assembly for a file
ViPERDSP/viper/utils/pffft.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pffft_core.dir/build.make CMakeFiles/pffft_core.dir/ViPERDSP/viper/utils/pffft.c.s
.PHONY : ViPERDSP/viper/utils/pffft.c.s

src/AudioFormat.o: src/AudioFormat.cpp.o
.PHONY : src/AudioFormat.o

# target to build an object file
src/AudioFormat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/AudioFormat.cpp.o
.PHONY : src/AudioFormat.cpp.o

src/AudioFormat.i: src/AudioFormat.cpp.i
.PHONY : src/AudioFormat.i

# target to preprocess a source file
src/AudioFormat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/AudioFormat.cpp.i
.PHONY : src/AudioFormat.cpp.i

src/AudioFormat.s: src/AudioFormat.cpp.s
.PHONY : src/AudioFormat.s

# target to generate assembly for a file
src/AudioFormat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/AudioFormat.cpp.s
.PHONY : src/AudioFormat.cpp.s

src/DspGraph.o: src/DspGraph.cpp.o
.PHONY : src/DspGraph.o

# target to build an object file
src/DspGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/DspGraph.cpp.o
.PHONY : src/DspGraph.cpp.o

src/DspGraph.i: src/DspGraph.cpp.i
.PHONY : src/DspGraph.i

# target to preprocess a source file
src/DspGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/DspGraph.cpp.i
.PHONY : src/DspGraph.cpp.i

src/DspGraph.s: src/DspGraph.cpp.s
.PHONY : src/DspGraph.s

# target to generate assembly for a file
src/DspGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/DspGraph.cpp.s
.PHONY : src/DspGraph.cpp.s

src/DspGraphSlots.o: src/DspGraphSlots.cpp.o
.PHONY : src/DspGraphSlots.o

# target to build an object file
src/DspGraphSlots.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/DspGraphSlots.cpp.o
.PHONY : src/DspGraphSlots.cpp.o

src/DspGraphSlots.i: src/DspGraphSlots.cpp.i
.PHONY : src/DspGraphSlots.i

# target to preprocess a source file
src/DspGraphSlots.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/DspGraphSlots.cpp.i
.PHONY : src/DspGraphSlots.cpp.i

src/DspGraphSlots.s: src/DspGraphSlots.cpp.s
.PHONY : src/DspGraphSlots.s

# target to generate assembly for a file
src/DspGraphSlots.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/DspGraphSlots.cpp.s
.PHONY : src/DspGraphSlots.cpp.s

src/DspResources.o: src/DspResources.cpp.o
.PHONY : src/DspResources.o

# target to build an object file
src/DspResources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/DspResources.cpp.o
.PHONY : src/DspResources.cpp.o

src/DspResources.i: src/DspResources.cpp.i
.PHONY : src/DspResources.i

# target to preprocess a source file
src/DspResources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/DspResources.cpp.i
.PHONY : src/DspResources.cpp.i

src/DspResources.s: src/DspResources.cpp.s
.PHONY : src/DspResources.s

# target to generate assembly for a file
src/DspResources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/DspResources.cpp.s
.PHONY : src/DspResources.cpp.s

src/GraphCrossfade.o: src/GraphCrossfade.cpp.o
.PHONY : src/GraphCrossfade.o

# target to build an object file
src/GraphCrossfade.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/GraphCrossfade.cpp.o
.PHONY : src/GraphCrossfade.cpp.o

src/GraphCrossfade.i: src/GraphCrossfade.cpp.i
.PHONY : src/GraphCrossfade.i

# target to preprocess a source file
src/GraphCrossfade.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/GraphCrossfade.cpp.i
.PHONY : src/GraphCrossfade.cpp.i

src/GraphCrossfade.s: src/GraphCrossfade.cpp.s
.PHONY : src/GraphCrossfade.s

# target to generate assembly for a file
src/GraphCrossfade.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/GraphCrossfade.cpp.s
.PHONY : src/GraphCrossfade.cpp.s

src/IemContext.o: src/IemContext.cpp.o
.PHONY : src/IemContext.o

# target to build an object file
src/IemContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemContext.cpp.o
.PHONY : src/IemContext.cpp.o

src/IemContext.i: src/IemContext.cpp.i
.PHONY : src/IemContext.i

# target to preprocess a source file
src/IemContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemContext.cpp.i
.PHONY : src/IemContext.cpp.i

src/IemContext.s: src/IemContext.cpp.s
.PHONY : src/IemContext.s

# target to generate assembly for a file
src/IemContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemContext.cpp.s
.PHONY : src/IemContext.cpp.s

src/IemGraph.o: src/IemGraph.cpp.o
.PHONY : src/IemGraph.o

# target to build an object file
src/IemGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemGraph.cpp.o
.PHONY : src/IemGraph.cpp.o

src/IemGraph.i: src/IemGraph.cpp.i
.PHONY : src/IemGraph.i

# target to preprocess a source file
src/IemGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemGraph.cpp.i
.PHONY : src/IemGraph.cpp.i

src/IemGraph.s: src/IemGraph.cpp.s
.PHONY : src/IemGraph.s

# target to generate assembly for a file
src/IemGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemGraph.cpp.s
.PHONY : src/IemGraph.cpp.s

src/IemGraphSlots.o: src/IemGraphSlots.cpp.o
.PHONY : src/IemGraphSlots.o

# target to build an object file
src/IemGraphSlots.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemGraphSlots.cpp.o
.PHONY : src/IemGraphSlots.cpp.o

src/IemGraphSlots.i: src/IemGraphSlots.cpp.i
.PHONY : src/IemGraphSlots.i

# target to preprocess a source file
src/IemGraphSlots.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemGraphSlots.cpp.i
.PHONY : src/IemGraphSlots.cpp.i

src/IemGraphSlots.s: src/IemGraphSlots.cpp.s
.PHONY : src/IemGraphSlots.s

# target to generate assembly for a file
src/IemGraphSlots.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemGraphSlots.cpp.s
.PHONY : src/IemGraphSlots.cpp.s

src/IemParameterMailbox.o: src/IemParameterMailbox.cpp.o
.PHONY : src/IemParameterMailbox.o

# target to build an object file
src/IemParameterMailbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemParameterMailbox.cpp.o
.PHONY : src/IemParameterMailbox.cpp.o

src/IemParameterMailbox.i: src/IemParameterMailbox.cpp.i
.PHONY : src/IemParameterMailbox.i

# target to preprocess a source file
src/IemParameterMailbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemParameterMailbox.cpp.i
.PHONY : src/IemParameterMailbox.cpp.i

src/IemParameterMailbox.s: src/IemParameterMailbox.cpp.s
.PHONY : src/IemParameterMailbox.s

# target to generate assembly for a file
src/IemParameterMailbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemParameterMailbox.cpp.s
.PHONY : src/IemParameterMailbox.cpp.s

src/IemResources.o: src/IemResources.cpp.o
.PHONY : src/IemResources.o

# target to build an object file
src/IemResources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemResources.cpp.o
.PHONY : src/IemResources.cpp.o

src/IemResources.i: src/IemResources.cpp.i
.PHONY : src/IemResources.i

# target to preprocess a source file
src/IemResources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemResources.cpp.i
.PHONY : src/IemResources.cpp.i

src/IemResources.s: src/IemResources.cpp.s
.PHONY : src/IemResources.s

# target to generate assembly for a file
src/IemResources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/IemResources.cpp.s
.PHONY : src/IemResources.cpp.s

src/ParameterMailbox.o: src/ParameterMailbox.cpp.o
.PHONY : src/ParameterMailbox.o

# target to build an object file
src/ParameterMailbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/ParameterMailbox.cpp.o
.PHONY : src/ParameterMailbox.cpp.o

src/ParameterMailbox.i: src/ParameterMailbox.cpp.i
.PHONY : src/ParameterMailbox.i

# target to preprocess a source file
src/ParameterMailbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/ParameterMailbox.cpp.i
.PHONY : src/ParameterMailbox.cpp.i

src/ParameterMailbox.s: src/ParameterMailbox.cpp.s
.PHONY : src/ParameterMailbox.s

# target to generate assembly for a file
src/ParameterMailbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/ParameterMailbox.cpp.s
.PHONY : src/ParameterMailbox.cpp.s

src/ViPER4Android.o: src/ViPER4Android.cpp.o
.PHONY : src/ViPER4Android.o

# target to build an object file
src/ViPER4Android.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/ViPER4Android.cpp.o
.PHONY : src/ViPER4Android.cpp.o

src/ViPER4Android.i: src/ViPER4Android.cpp.i
.PHONY : src/ViPER4Android.i

# target to preprocess a source file
src/ViPER4Android.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/ViPER4Android.cpp.i
.PHONY : src/ViPER4Android.cpp.i

src/ViPER4Android.s: src/ViPER4Android.cpp.s
.PHONY : src/ViPER4Android.s

# target to generate assembly for a file
src/ViPER4Android.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/ViPER4Android.cpp.s
.PHONY : src/ViPER4Android.cpp.s

src/ViperContext.o: src/ViperContext.cpp.o
.PHONY : src/ViperContext.o

# target to build an object file
src/ViperContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/ViperContext.cpp.o
.PHONY : src/ViperContext.cpp.o

src/ViperContext.i: src/ViperContext.cpp.i
.PHONY : src/ViperContext.i

# target to preprocess a source file
src/ViperContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/ViperContext.cpp.i
.PHONY : src/ViperContext.cpp.i

src/ViperContext.s: src/ViperContext.cpp.s
.PHONY : src/ViperContext.s

# target to generate assembly for a file
src/ViperContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v4a_re.dir/build.make CMakeFiles/v4a_re.dir/src/ViperContext.cpp.s
.PHONY : src/ViperContext.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IEMDSP"
	@echo "... ViPERDSP"
	@echo "... pffft_core"
	@echo "... v4a_re"
	@echo "... ViPERDSP/viper/utils/pffft.o"
	@echo "... ViPERDSP/viper/utils/pffft.i"
	@echo "... ViPERDSP/viper/utils/pffft.s"
	@echo "... src/AudioFormat.o"
	@echo "... src/AudioFormat.i"
	@echo "... src/AudioFormat.s"
	@echo "... src/DspGraph.o"
	@echo "... src/DspGraph.i"
	@echo "... src/DspGraph.s"
	@echo "... src/DspGraphSlots.o"
	@echo "... src/DspGraphSlots.i"
	@echo "... src/DspGraphSlots.s"
	@echo "... src/DspResources.o"
	@echo "... src/DspResources.i"
	@echo "... src/DspResources.s"
	@echo "... src/GraphCrossfade.o"
	@echo "... src/GraphCrossfade.i"
	@echo "... src/GraphCrossfade.s"
	@echo "... src/IemContext.o"
	@echo "... src/IemContext.i"
	@echo "... src/IemContext.s"
	@echo "... src/IemGraph.o"
	@echo "... src/IemGraph.i"
	@echo "... src/IemGraph.s"
	@echo "... src/IemGraphSlots.o"
	@echo "... src/IemGraphSlots.i"
	@echo "... src/IemGraphSlots.s"
	@echo "... src/IemParameterMailbox.o"
	@echo "... src/IemParameterMailbox.i"
	@echo "... src/IemParameterMailbox.s"
	@echo "... src/IemResources.o"
	@echo "... src/IemResources.i"
	@echo "... src/IemResources.s"
	@echo "... src/ParameterMailbox.o"
	@echo "... src/ParameterMailbox.i"
	@echo "... src/ParameterMailbox.s"
	@echo "... src/ViPER4Android.o"
	@echo "... src/ViPER4Android.i"
	@echo "... src/ViPER4Android.s"
	@echo "... src/ViperContext.o"
	@echo "... src/ViperContext.i"
	@echo "... src/ViperContext.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

